openapi: 3.0.3
info:
  description: FY24卒Web開発研修6班のAPI仕様書です
  title: Web開発研修6班 API
  version: 1.0.0
paths:
  /:
    get:
      operationId: healthCheck
      responses:
        "204":
          description: No Content
      summary: APIのセルフチェック
      tags:
      - operation
  /posts:
    get:
      operationId: listPosts
      responses:
        "202":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SchemaPostResponse'
                type: array
          description: Accepted
      summary: 投稿の一覧を取得
      tags:
      - post
  /signin:
    post:
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchemaLoginRequest'
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchemaUserResponse'
          description: Accepted
      summary: ユーザのログインを実行
      tags:
      - auth
  /signout:
    post:
      operationId: signOut
      responses:
        "204":
          description: No Content
      summary: ユーザのログアウトを実行
      tags:
      - auth
  /user:
    get:
      operationId: getCurrentUser
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchemaUserResponse'
          description: Accepted
      summary: 現在ログインしているユーザを取得
      tags:
      - auth
components:
  schemas:
    SchemaLoginRequest:
      properties:
        password:
          type: string
        user_name:
          type: string
      type: object
    SchemaPostResponse:
      properties:
        body:
          type: string
        post_id:
          type: integer
        title:
          type: string
        user_id:
          type: integer
        user_name:
          type: string
      type: object
    SchemaUserResponse:
      properties:
        user_id:
          type: integer
        user_name:
          type: string
      type: object
