

on: 
  push:
    paths:
    #todo pushされるたびに動くのは危険
      - ".github/**"


env:
  AWS_REGION: ap-northeast-1
  REPOSITORY_NAME_BACKEND: dena-training-2024-team-6-backend
  REPOSITORY_NAME_FRONTEND: dena-training-2024-team-6-frontend
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECS_CLUSTER: dena-training-2024
  ECS_SERVICE: dena-training-2024-team-6
  BUCKET_PREFIX: team-6
  VITE_API_ENDPOINT_PATH: https://team-6_bk.member0005.track-bootcamp.run

jobs:
  backend-build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Build
        working-directory: ./backend
        run: go build -o myapp
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-bin
          path: |
            backend/myapp
            docker/backend-ci.Dockerfile