name: Backend-CI

on: 
  push:
    paths:
      - "backend/**"

defaults:
  run:
    working-directory: backend

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2
      
      - name: build container
        run: docker compose -f ../docker-compose.yml up -d
      
      - name: initial db setup
        run: |
        docker-compose exec db sh -c "mysql < /sqlscripts/create.sql"
        docker-compose exec db sh -c "mysql training < /sqlscripts/insert.sql"

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run Test
        run: go test -v ./... -coverprofile=coverage.out

      - name: Upload Octocov
        uses: k1LoW/octocov-action@v0

  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.2
      - name: OS Version
        run: cat /etc/os-release

      - name: Go Version
        run: go version

      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: backend/
