

on: 
  push:
    # mainのみ
    branches:
      - main
      - feature/frontenddeploy
    paths:
    #todo pushされるたびに動くのは危険
      - ".github/**"
      - "backend/**"
      - "frontend/**"
    


env:
  AWS_REGION: ap-northeast-1
  REPOSITORY_NAME_BACKEND: dena-training-2024-team-6-backend
  REPOSITORY_NAME_FRONTEND: dena-training-2024-team-6-frontend
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECS_CLUSTER: dena-training-2024
  ECS_SERVICE: dena-training-2024-team-6
  BUCKET_PREFIX: team-6
  VITE_API_ENDPOINT_PATH: https://team-6_bk.member0005.track-bootcamp.run

jobs:
  
  # frontendをbuildしてartifactに保存する
  frontend-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: pnpm install
      run: npm install -g pnpm

    - name: Build
      working-directory: ./frontend
      run: pnpm build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-bin
        path: |
          frontend
          docker/frontend-ci.Dockerfile

  frontend-s3-push:
    runs-on: ubuntu-latest
    needs: [frontend-build]
#    if: github.ref == 'refs/heads/deploy'

    steps:
    - name: Download frontend build artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-bin
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

    - name: Sync files to S3
      run: aws s3 sync frontend/dist s3://dena-training-2024/$BUCKET_PREFIX --delete
