name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.2
      - name: OS Version
        run: cat /etc/os-release

      - name: Go Version
        run: go version

      - name: cd backend
        run: |
          cd backend
          pwd
      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest